
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 8080
      name: http
      targetPort: 8080
      nodePort: 30041

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: bhoomikars/hello:latest
          ports:
            - containerPort: 8080
#          livenessProbe:
#            httpGet:
#              path: /healthcheck
#              port: 8025
#            initialDelaySeconds: 30
#            timeoutSeconds: 1